#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

# Check case version is correct
solids4Foam::convertCaseFormat .

# Create meshes
solids4Foam::runApplication -s solid blockMesh -region solid
solids4Foam::runApplication -s fluid blockMesh -region fluid

# Set water volume fraction field (alpha) in the fluid
cp 0/fluid/alpha1.org 0/fluid/alpha1
(cd 0/fluid && ln -s alpha1 alpha.water)

solids4Foam::runApplication setFields -region fluid

# Decompose all regions
solids4Foam::runApplication decomposePar -allRegions

# Run two-way FSI solver in parallel
solids4Foam::runParallel -np ${nProcs} solids4Foam -parallel

# Reconstruct all regions
solids4Foam::runApplication reconstructPar -allRegions


