#!/bin/bash

cd "${0%/*}" || exit 1

. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions

if [ -f 0/fluid/alpha1.org ]; then
    cp 0/fluid/alpha1.org 0/fluid/alpha1
fi

runApplication blockMesh -region fluid
runApplication blockMesh -region solid

runApplication checkMesh -region fluid
runApplication checkMesh -region solid

runApplication setFields -region fluid

runApplication solids4Foam
