#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Source solids4Foam scripts
source solids4FoamScripts.sh

# Check case version is correct
solids4Foam::convertCaseFormat .

# Decompose all regions
solids4Foam::runApplication -s fluid decomposePar -region fluid
solids4Foam::runApplication -s solid decomposePar -region solid

# Run two-way FSI solver in parallel
solids4Foam::runParallel solids4Foam

# Reconstruct all regions
solids4Foam::runApplication -s fluid reconstructPar -region fluid
solids4Foam::runApplication -s solid reconstructPar -region solid


